/**
 * @deprecated — Import from "@/services/usePublicContent" instead.
 * This file re-exports everything for backward compatibility.
 */
export {
  usePublicPortfolio,
  usePublicEvents,
  usePublicHero,
  usePublicIncubators,
  usePublicPartners,
  usePublicSocialLinks,
  usePublicStartupsTicker,
  usePublicTeam,
  usePublicMentors,
  usePublicBoard,
  usePublicStatistics,
  usePublicInfrastructure,
  usePublicStartupPortfolio,
  usePublicEventsCalendar,
  usePublicVisionRoadmap,
  usePublicWhatWeDo,
  usePublicStudentDashboard,
  usePublicStartupEvents,
  usePublicRewards,
  usePublicInternshipRegistration,
  usePublicInternshipCalendar,
  usePublicInstitutionsClubs,
  usePublicStartupBlog,
  usePublicStartupFunding,
  usePublicInvestors,
  usePublicAhubNetwork,
  usePublicDistinguishedVisitors,
  usePublicPartnersPage,
  usePublicPartnerItems,
  usePublicImpact,
  usePublicOperationalModel,
  usePublicJoinUs,
  usePublicPitchToUs,
  usePublicStartupRegistration,
} from "@/services/usePublicContent";
