/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as IncubatorsRouteImport } from './routes/incubators'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StudentsInternshipRegistrationRouteImport } from './routes/students/internship-registration'
import { Route as StudentsDashboardRouteImport } from './routes/students/dashboard'
import { Route as StartupsStartupRegistrationRouteImport } from './routes/startups/startup-registration'
import { Route as StartupsStartupPortfolioRouteImport } from './routes/startups/startup-portfolio'
import { Route as StartupsStartupFundingRouteImport } from './routes/startups/startup-funding'
import { Route as StartupsBlogRouteImport } from './routes/startups/blog'
import { Route as ProgramsPitchToUsRouteImport } from './routes/programs/pitch-to-us'
import { Route as ProgramsJoinUsRouteImport } from './routes/programs/join-us'
import { Route as EventsStartupsEventsRouteImport } from './routes/events/startups-events'
import { Route as EventsEventRegistrationRouteImport } from './routes/events/event-registration'
import { Route as EventsCaseStudiesRouteImport } from './routes/events/case-studies'
import { Route as EventsCalendarRouteImport } from './routes/events/calendar'
import { Route as EcosystemPartnersRouteImport } from './routes/ecosystem/partners'
import { Route as EcosystemMentorsRouteImport } from './routes/ecosystem/mentors'
import { Route as EcosystemInvestorsRouteImport } from './routes/ecosystem/investors'
import { Route as EcosystemInfrastructureRouteImport } from './routes/ecosystem/infrastructure'
import { Route as ApproachOperationalModelRouteImport } from './routes/approach/operational-model'
import { Route as AdminVisitorsRouteImport } from './routes/admin/visitors'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as AdminPartnersLogosRouteImport } from './routes/admin/partners-logos'
import { Route as AdminMeshNetworkRouteImport } from './routes/admin/mesh-network'
import { Route as AdminMentorsRouteImport } from './routes/admin/mentors'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLatestEventsRouteImport } from './routes/admin/latest-events'
import { Route as AdminInternshipRegistrationRouteImport } from './routes/admin/internship-registration'
import { Route as AdminInfrastructureRouteImport } from './routes/admin/infrastructure'
import { Route as AdminFindUsOnRouteImport } from './routes/admin/find-us-on'
import { Route as AdminBoardRouteImport } from './routes/admin/board'
import { Route as AdminAssociatedWithRouteImport } from './routes/admin/associated-with'
import { Route as AchieveReportsRouteImport } from './routes/achieve/reports'
import { Route as AchieveImpactRouteImport } from './routes/achieve/impact'
import { Route as AboutVisionRoadmapRouteImport } from './routes/about/vision-roadmap'
import { Route as AboutTeamRouteImport } from './routes/about/team'
import { Route as AboutRewardsRouteImport } from './routes/about/rewards'
import { Route as AboutPressRouteImport } from './routes/about/press'
import { Route as AboutMentorsRouteImport } from './routes/about/mentors'
import { Route as AboutBoardRouteImport } from './routes/about/board'
import { Route as SectionSlugRouteImport } from './routes/$section/$slug'

const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const IncubatorsRoute = IncubatorsRouteImport.update({
  id: '/incubators',
  path: '/incubators',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsInternshipRegistrationRoute =
  StudentsInternshipRegistrationRouteImport.update({
    id: '/students/internship-registration',
    path: '/students/internship-registration',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentsDashboardRoute = StudentsDashboardRouteImport.update({
  id: '/students/dashboard',
  path: '/students/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsStartupRegistrationRoute =
  StartupsStartupRegistrationRouteImport.update({
    id: '/startups/startup-registration',
    path: '/startups/startup-registration',
    getParentRoute: () => rootRouteImport,
  } as any)
const StartupsStartupPortfolioRoute =
  StartupsStartupPortfolioRouteImport.update({
    id: '/startups/startup-portfolio',
    path: '/startups/startup-portfolio',
    getParentRoute: () => rootRouteImport,
  } as any)
const StartupsStartupFundingRoute = StartupsStartupFundingRouteImport.update({
  id: '/startups/startup-funding',
  path: '/startups/startup-funding',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsBlogRoute = StartupsBlogRouteImport.update({
  id: '/startups/blog',
  path: '/startups/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsPitchToUsRoute = ProgramsPitchToUsRouteImport.update({
  id: '/programs/pitch-to-us',
  path: '/programs/pitch-to-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsJoinUsRoute = ProgramsJoinUsRouteImport.update({
  id: '/programs/join-us',
  path: '/programs/join-us',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsStartupsEventsRoute = EventsStartupsEventsRouteImport.update({
  id: '/events/startups-events',
  path: '/events/startups-events',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventRegistrationRoute = EventsEventRegistrationRouteImport.update({
  id: '/events/event-registration',
  path: '/events/event-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCaseStudiesRoute = EventsCaseStudiesRouteImport.update({
  id: '/events/case-studies',
  path: '/events/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCalendarRoute = EventsCalendarRouteImport.update({
  id: '/events/calendar',
  path: '/events/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemPartnersRoute = EcosystemPartnersRouteImport.update({
  id: '/ecosystem/partners',
  path: '/ecosystem/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemMentorsRoute = EcosystemMentorsRouteImport.update({
  id: '/ecosystem/mentors',
  path: '/ecosystem/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemInvestorsRoute = EcosystemInvestorsRouteImport.update({
  id: '/ecosystem/investors',
  path: '/ecosystem/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemInfrastructureRoute = EcosystemInfrastructureRouteImport.update({
  id: '/ecosystem/infrastructure',
  path: '/ecosystem/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachOperationalModelRoute =
  ApproachOperationalModelRouteImport.update({
    id: '/approach/operational-model',
    path: '/approach/operational-model',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminVisitorsRoute = AdminVisitorsRouteImport.update({
  id: '/admin/visitors',
  path: '/admin/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnersLogosRoute = AdminPartnersLogosRouteImport.update({
  id: '/admin/partners-logos',
  path: '/admin/partners-logos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMeshNetworkRoute = AdminMeshNetworkRouteImport.update({
  id: '/admin/mesh-network',
  path: '/admin/mesh-network',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMentorsRoute = AdminMentorsRouteImport.update({
  id: '/admin/mentors',
  path: '/admin/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLatestEventsRoute = AdminLatestEventsRouteImport.update({
  id: '/admin/latest-events',
  path: '/admin/latest-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInternshipRegistrationRoute =
  AdminInternshipRegistrationRouteImport.update({
    id: '/admin/internship-registration',
    path: '/admin/internship-registration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminInfrastructureRoute = AdminInfrastructureRouteImport.update({
  id: '/admin/infrastructure',
  path: '/admin/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFindUsOnRoute = AdminFindUsOnRouteImport.update({
  id: '/admin/find-us-on',
  path: '/admin/find-us-on',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBoardRoute = AdminBoardRouteImport.update({
  id: '/admin/board',
  path: '/admin/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssociatedWithRoute = AdminAssociatedWithRouteImport.update({
  id: '/admin/associated-with',
  path: '/admin/associated-with',
  getParentRoute: () => rootRouteImport,
} as any)
const AchieveReportsRoute = AchieveReportsRouteImport.update({
  id: '/achieve/reports',
  path: '/achieve/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AchieveImpactRoute = AchieveImpactRouteImport.update({
  id: '/achieve/impact',
  path: '/achieve/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutVisionRoadmapRoute = AboutVisionRoadmapRouteImport.update({
  id: '/about/vision-roadmap',
  path: '/about/vision-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTeamRoute = AboutTeamRouteImport.update({
  id: '/about/team',
  path: '/about/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRewardsRoute = AboutRewardsRouteImport.update({
  id: '/about/rewards',
  path: '/about/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPressRoute = AboutPressRouteImport.update({
  id: '/about/press',
  path: '/about/press',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMentorsRoute = AboutMentorsRouteImport.update({
  id: '/about/mentors',
  path: '/about/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutBoardRoute = AboutBoardRouteImport.update({
  id: '/about/board',
  path: '/about/board',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSlugRoute = SectionSlugRouteImport.update({
  id: '/$section/$slug',
  path: '/$section/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/incubators': typeof IncubatorsRoute
  '/mentors': typeof MentorsRoute
  '/$section/$slug': typeof SectionSlugRoute
  '/about/board': typeof AboutBoardRoute
  '/about/mentors': typeof AboutMentorsRoute
  '/about/press': typeof AboutPressRoute
  '/about/rewards': typeof AboutRewardsRoute
  '/about/team': typeof AboutTeamRoute
  '/about/vision-roadmap': typeof AboutVisionRoadmapRoute
  '/achieve/impact': typeof AchieveImpactRoute
  '/achieve/reports': typeof AchieveReportsRoute
  '/admin/associated-with': typeof AdminAssociatedWithRoute
  '/admin/board': typeof AdminBoardRoute
  '/admin/find-us-on': typeof AdminFindUsOnRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/internship-registration': typeof AdminInternshipRegistrationRoute
  '/admin/latest-events': typeof AdminLatestEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/mesh-network': typeof AdminMeshNetworkRoute
  '/admin/partners-logos': typeof AdminPartnersLogosRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/approach/operational-model': typeof ApproachOperationalModelRoute
  '/ecosystem/infrastructure': typeof EcosystemInfrastructureRoute
  '/ecosystem/investors': typeof EcosystemInvestorsRoute
  '/ecosystem/mentors': typeof EcosystemMentorsRoute
  '/ecosystem/partners': typeof EcosystemPartnersRoute
  '/events/calendar': typeof EventsCalendarRoute
  '/events/case-studies': typeof EventsCaseStudiesRoute
  '/events/event-registration': typeof EventsEventRegistrationRoute
  '/events/startups-events': typeof EventsStartupsEventsRoute
  '/programs/join-us': typeof ProgramsJoinUsRoute
  '/programs/pitch-to-us': typeof ProgramsPitchToUsRoute
  '/startups/blog': typeof StartupsBlogRoute
  '/startups/startup-funding': typeof StartupsStartupFundingRoute
  '/startups/startup-portfolio': typeof StartupsStartupPortfolioRoute
  '/startups/startup-registration': typeof StartupsStartupRegistrationRoute
  '/students/dashboard': typeof StudentsDashboardRoute
  '/students/internship-registration': typeof StudentsInternshipRegistrationRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/incubators': typeof IncubatorsRoute
  '/mentors': typeof MentorsRoute
  '/$section/$slug': typeof SectionSlugRoute
  '/about/board': typeof AboutBoardRoute
  '/about/mentors': typeof AboutMentorsRoute
  '/about/press': typeof AboutPressRoute
  '/about/rewards': typeof AboutRewardsRoute
  '/about/team': typeof AboutTeamRoute
  '/about/vision-roadmap': typeof AboutVisionRoadmapRoute
  '/achieve/impact': typeof AchieveImpactRoute
  '/achieve/reports': typeof AchieveReportsRoute
  '/admin/associated-with': typeof AdminAssociatedWithRoute
  '/admin/board': typeof AdminBoardRoute
  '/admin/find-us-on': typeof AdminFindUsOnRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/internship-registration': typeof AdminInternshipRegistrationRoute
  '/admin/latest-events': typeof AdminLatestEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/mesh-network': typeof AdminMeshNetworkRoute
  '/admin/partners-logos': typeof AdminPartnersLogosRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/approach/operational-model': typeof ApproachOperationalModelRoute
  '/ecosystem/infrastructure': typeof EcosystemInfrastructureRoute
  '/ecosystem/investors': typeof EcosystemInvestorsRoute
  '/ecosystem/mentors': typeof EcosystemMentorsRoute
  '/ecosystem/partners': typeof EcosystemPartnersRoute
  '/events/calendar': typeof EventsCalendarRoute
  '/events/case-studies': typeof EventsCaseStudiesRoute
  '/events/event-registration': typeof EventsEventRegistrationRoute
  '/events/startups-events': typeof EventsStartupsEventsRoute
  '/programs/join-us': typeof ProgramsJoinUsRoute
  '/programs/pitch-to-us': typeof ProgramsPitchToUsRoute
  '/startups/blog': typeof StartupsBlogRoute
  '/startups/startup-funding': typeof StartupsStartupFundingRoute
  '/startups/startup-portfolio': typeof StartupsStartupPortfolioRoute
  '/startups/startup-registration': typeof StartupsStartupRegistrationRoute
  '/students/dashboard': typeof StudentsDashboardRoute
  '/students/internship-registration': typeof StudentsInternshipRegistrationRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/incubators': typeof IncubatorsRoute
  '/mentors': typeof MentorsRoute
  '/$section/$slug': typeof SectionSlugRoute
  '/about/board': typeof AboutBoardRoute
  '/about/mentors': typeof AboutMentorsRoute
  '/about/press': typeof AboutPressRoute
  '/about/rewards': typeof AboutRewardsRoute
  '/about/team': typeof AboutTeamRoute
  '/about/vision-roadmap': typeof AboutVisionRoadmapRoute
  '/achieve/impact': typeof AchieveImpactRoute
  '/achieve/reports': typeof AchieveReportsRoute
  '/admin/associated-with': typeof AdminAssociatedWithRoute
  '/admin/board': typeof AdminBoardRoute
  '/admin/find-us-on': typeof AdminFindUsOnRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/internship-registration': typeof AdminInternshipRegistrationRoute
  '/admin/latest-events': typeof AdminLatestEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/mesh-network': typeof AdminMeshNetworkRoute
  '/admin/partners-logos': typeof AdminPartnersLogosRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/approach/operational-model': typeof ApproachOperationalModelRoute
  '/ecosystem/infrastructure': typeof EcosystemInfrastructureRoute
  '/ecosystem/investors': typeof EcosystemInvestorsRoute
  '/ecosystem/mentors': typeof EcosystemMentorsRoute
  '/ecosystem/partners': typeof EcosystemPartnersRoute
  '/events/calendar': typeof EventsCalendarRoute
  '/events/case-studies': typeof EventsCaseStudiesRoute
  '/events/event-registration': typeof EventsEventRegistrationRoute
  '/events/startups-events': typeof EventsStartupsEventsRoute
  '/programs/join-us': typeof ProgramsJoinUsRoute
  '/programs/pitch-to-us': typeof ProgramsPitchToUsRoute
  '/startups/blog': typeof StartupsBlogRoute
  '/startups/startup-funding': typeof StartupsStartupFundingRoute
  '/startups/startup-portfolio': typeof StartupsStartupPortfolioRoute
  '/startups/startup-registration': typeof StartupsStartupRegistrationRoute
  '/students/dashboard': typeof StudentsDashboardRoute
  '/students/internship-registration': typeof StudentsInternshipRegistrationRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/incubators'
    | '/mentors'
    | '/$section/$slug'
    | '/about/board'
    | '/about/mentors'
    | '/about/press'
    | '/about/rewards'
    | '/about/team'
    | '/about/vision-roadmap'
    | '/achieve/impact'
    | '/achieve/reports'
    | '/admin/associated-with'
    | '/admin/board'
    | '/admin/find-us-on'
    | '/admin/infrastructure'
    | '/admin/internship-registration'
    | '/admin/latest-events'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/mesh-network'
    | '/admin/partners-logos'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/visitors'
    | '/approach/operational-model'
    | '/ecosystem/infrastructure'
    | '/ecosystem/investors'
    | '/ecosystem/mentors'
    | '/ecosystem/partners'
    | '/events/calendar'
    | '/events/case-studies'
    | '/events/event-registration'
    | '/events/startups-events'
    | '/programs/join-us'
    | '/programs/pitch-to-us'
    | '/startups/blog'
    | '/startups/startup-funding'
    | '/startups/startup-portfolio'
    | '/startups/startup-registration'
    | '/students/dashboard'
    | '/students/internship-registration'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/incubators'
    | '/mentors'
    | '/$section/$slug'
    | '/about/board'
    | '/about/mentors'
    | '/about/press'
    | '/about/rewards'
    | '/about/team'
    | '/about/vision-roadmap'
    | '/achieve/impact'
    | '/achieve/reports'
    | '/admin/associated-with'
    | '/admin/board'
    | '/admin/find-us-on'
    | '/admin/infrastructure'
    | '/admin/internship-registration'
    | '/admin/latest-events'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/mesh-network'
    | '/admin/partners-logos'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/visitors'
    | '/approach/operational-model'
    | '/ecosystem/infrastructure'
    | '/ecosystem/investors'
    | '/ecosystem/mentors'
    | '/ecosystem/partners'
    | '/events/calendar'
    | '/events/case-studies'
    | '/events/event-registration'
    | '/events/startups-events'
    | '/programs/join-us'
    | '/programs/pitch-to-us'
    | '/startups/blog'
    | '/startups/startup-funding'
    | '/startups/startup-portfolio'
    | '/startups/startup-registration'
    | '/students/dashboard'
    | '/students/internship-registration'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/incubators'
    | '/mentors'
    | '/$section/$slug'
    | '/about/board'
    | '/about/mentors'
    | '/about/press'
    | '/about/rewards'
    | '/about/team'
    | '/about/vision-roadmap'
    | '/achieve/impact'
    | '/achieve/reports'
    | '/admin/associated-with'
    | '/admin/board'
    | '/admin/find-us-on'
    | '/admin/infrastructure'
    | '/admin/internship-registration'
    | '/admin/latest-events'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/mesh-network'
    | '/admin/partners-logos'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/visitors'
    | '/approach/operational-model'
    | '/ecosystem/infrastructure'
    | '/ecosystem/investors'
    | '/ecosystem/mentors'
    | '/ecosystem/partners'
    | '/events/calendar'
    | '/events/case-studies'
    | '/events/event-registration'
    | '/events/startups-events'
    | '/programs/join-us'
    | '/programs/pitch-to-us'
    | '/startups/blog'
    | '/startups/startup-funding'
    | '/startups/startup-portfolio'
    | '/startups/startup-registration'
    | '/students/dashboard'
    | '/students/internship-registration'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncubatorsRoute: typeof IncubatorsRoute
  MentorsRoute: typeof MentorsRoute
  SectionSlugRoute: typeof SectionSlugRoute
  AboutBoardRoute: typeof AboutBoardRoute
  AboutMentorsRoute: typeof AboutMentorsRoute
  AboutPressRoute: typeof AboutPressRoute
  AboutRewardsRoute: typeof AboutRewardsRoute
  AboutTeamRoute: typeof AboutTeamRoute
  AboutVisionRoadmapRoute: typeof AboutVisionRoadmapRoute
  AchieveImpactRoute: typeof AchieveImpactRoute
  AchieveReportsRoute: typeof AchieveReportsRoute
  AdminAssociatedWithRoute: typeof AdminAssociatedWithRoute
  AdminBoardRoute: typeof AdminBoardRoute
  AdminFindUsOnRoute: typeof AdminFindUsOnRoute
  AdminInfrastructureRoute: typeof AdminInfrastructureRoute
  AdminInternshipRegistrationRoute: typeof AdminInternshipRegistrationRoute
  AdminLatestEventsRoute: typeof AdminLatestEventsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMentorsRoute: typeof AdminMentorsRoute
  AdminMeshNetworkRoute: typeof AdminMeshNetworkRoute
  AdminPartnersLogosRoute: typeof AdminPartnersLogosRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminVisitorsRoute: typeof AdminVisitorsRoute
  ApproachOperationalModelRoute: typeof ApproachOperationalModelRoute
  EcosystemInfrastructureRoute: typeof EcosystemInfrastructureRoute
  EcosystemInvestorsRoute: typeof EcosystemInvestorsRoute
  EcosystemMentorsRoute: typeof EcosystemMentorsRoute
  EcosystemPartnersRoute: typeof EcosystemPartnersRoute
  EventsCalendarRoute: typeof EventsCalendarRoute
  EventsCaseStudiesRoute: typeof EventsCaseStudiesRoute
  EventsEventRegistrationRoute: typeof EventsEventRegistrationRoute
  EventsStartupsEventsRoute: typeof EventsStartupsEventsRoute
  ProgramsJoinUsRoute: typeof ProgramsJoinUsRoute
  ProgramsPitchToUsRoute: typeof ProgramsPitchToUsRoute
  StartupsBlogRoute: typeof StartupsBlogRoute
  StartupsStartupFundingRoute: typeof StartupsStartupFundingRoute
  StartupsStartupPortfolioRoute: typeof StartupsStartupPortfolioRoute
  StartupsStartupRegistrationRoute: typeof StartupsStartupRegistrationRoute
  StudentsDashboardRoute: typeof StudentsDashboardRoute
  StudentsInternshipRegistrationRoute: typeof StudentsInternshipRegistrationRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incubators': {
      id: '/incubators'
      path: '/incubators'
      fullPath: '/incubators'
      preLoaderRoute: typeof IncubatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/internship-registration': {
      id: '/students/internship-registration'
      path: '/students/internship-registration'
      fullPath: '/students/internship-registration'
      preLoaderRoute: typeof StudentsInternshipRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/dashboard': {
      id: '/students/dashboard'
      path: '/students/dashboard'
      fullPath: '/students/dashboard'
      preLoaderRoute: typeof StudentsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups/startup-registration': {
      id: '/startups/startup-registration'
      path: '/startups/startup-registration'
      fullPath: '/startups/startup-registration'
      preLoaderRoute: typeof StartupsStartupRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups/startup-portfolio': {
      id: '/startups/startup-portfolio'
      path: '/startups/startup-portfolio'
      fullPath: '/startups/startup-portfolio'
      preLoaderRoute: typeof StartupsStartupPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups/startup-funding': {
      id: '/startups/startup-funding'
      path: '/startups/startup-funding'
      fullPath: '/startups/startup-funding'
      preLoaderRoute: typeof StartupsStartupFundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups/blog': {
      id: '/startups/blog'
      path: '/startups/blog'
      fullPath: '/startups/blog'
      preLoaderRoute: typeof StartupsBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/pitch-to-us': {
      id: '/programs/pitch-to-us'
      path: '/programs/pitch-to-us'
      fullPath: '/programs/pitch-to-us'
      preLoaderRoute: typeof ProgramsPitchToUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/join-us': {
      id: '/programs/join-us'
      path: '/programs/join-us'
      fullPath: '/programs/join-us'
      preLoaderRoute: typeof ProgramsJoinUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/startups-events': {
      id: '/events/startups-events'
      path: '/events/startups-events'
      fullPath: '/events/startups-events'
      preLoaderRoute: typeof EventsStartupsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/event-registration': {
      id: '/events/event-registration'
      path: '/events/event-registration'
      fullPath: '/events/event-registration'
      preLoaderRoute: typeof EventsEventRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/case-studies': {
      id: '/events/case-studies'
      path: '/events/case-studies'
      fullPath: '/events/case-studies'
      preLoaderRoute: typeof EventsCaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/calendar': {
      id: '/events/calendar'
      path: '/events/calendar'
      fullPath: '/events/calendar'
      preLoaderRoute: typeof EventsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem/partners': {
      id: '/ecosystem/partners'
      path: '/ecosystem/partners'
      fullPath: '/ecosystem/partners'
      preLoaderRoute: typeof EcosystemPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem/mentors': {
      id: '/ecosystem/mentors'
      path: '/ecosystem/mentors'
      fullPath: '/ecosystem/mentors'
      preLoaderRoute: typeof EcosystemMentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem/investors': {
      id: '/ecosystem/investors'
      path: '/ecosystem/investors'
      fullPath: '/ecosystem/investors'
      preLoaderRoute: typeof EcosystemInvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem/infrastructure': {
      id: '/ecosystem/infrastructure'
      path: '/ecosystem/infrastructure'
      fullPath: '/ecosystem/infrastructure'
      preLoaderRoute: typeof EcosystemInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach/operational-model': {
      id: '/approach/operational-model'
      path: '/approach/operational-model'
      fullPath: '/approach/operational-model'
      preLoaderRoute: typeof ApproachOperationalModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visitors': {
      id: '/admin/visitors'
      path: '/admin/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partners-logos': {
      id: '/admin/partners-logos'
      path: '/admin/partners-logos'
      fullPath: '/admin/partners-logos'
      preLoaderRoute: typeof AdminPartnersLogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mesh-network': {
      id: '/admin/mesh-network'
      path: '/admin/mesh-network'
      fullPath: '/admin/mesh-network'
      preLoaderRoute: typeof AdminMeshNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mentors': {
      id: '/admin/mentors'
      path: '/admin/mentors'
      fullPath: '/admin/mentors'
      preLoaderRoute: typeof AdminMentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/latest-events': {
      id: '/admin/latest-events'
      path: '/admin/latest-events'
      fullPath: '/admin/latest-events'
      preLoaderRoute: typeof AdminLatestEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/internship-registration': {
      id: '/admin/internship-registration'
      path: '/admin/internship-registration'
      fullPath: '/admin/internship-registration'
      preLoaderRoute: typeof AdminInternshipRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/infrastructure': {
      id: '/admin/infrastructure'
      path: '/admin/infrastructure'
      fullPath: '/admin/infrastructure'
      preLoaderRoute: typeof AdminInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/find-us-on': {
      id: '/admin/find-us-on'
      path: '/admin/find-us-on'
      fullPath: '/admin/find-us-on'
      preLoaderRoute: typeof AdminFindUsOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/board': {
      id: '/admin/board'
      path: '/admin/board'
      fullPath: '/admin/board'
      preLoaderRoute: typeof AdminBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/associated-with': {
      id: '/admin/associated-with'
      path: '/admin/associated-with'
      fullPath: '/admin/associated-with'
      preLoaderRoute: typeof AdminAssociatedWithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achieve/reports': {
      id: '/achieve/reports'
      path: '/achieve/reports'
      fullPath: '/achieve/reports'
      preLoaderRoute: typeof AchieveReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achieve/impact': {
      id: '/achieve/impact'
      path: '/achieve/impact'
      fullPath: '/achieve/impact'
      preLoaderRoute: typeof AchieveImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/vision-roadmap': {
      id: '/about/vision-roadmap'
      path: '/about/vision-roadmap'
      fullPath: '/about/vision-roadmap'
      preLoaderRoute: typeof AboutVisionRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/team': {
      id: '/about/team'
      path: '/about/team'
      fullPath: '/about/team'
      preLoaderRoute: typeof AboutTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/rewards': {
      id: '/about/rewards'
      path: '/about/rewards'
      fullPath: '/about/rewards'
      preLoaderRoute: typeof AboutRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/press': {
      id: '/about/press'
      path: '/about/press'
      fullPath: '/about/press'
      preLoaderRoute: typeof AboutPressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/mentors': {
      id: '/about/mentors'
      path: '/about/mentors'
      fullPath: '/about/mentors'
      preLoaderRoute: typeof AboutMentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/board': {
      id: '/about/board'
      path: '/about/board'
      fullPath: '/about/board'
      preLoaderRoute: typeof AboutBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section/$slug': {
      id: '/$section/$slug'
      path: '/$section/$slug'
      fullPath: '/$section/$slug'
      preLoaderRoute: typeof SectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncubatorsRoute: IncubatorsRoute,
  MentorsRoute: MentorsRoute,
  SectionSlugRoute: SectionSlugRoute,
  AboutBoardRoute: AboutBoardRoute,
  AboutMentorsRoute: AboutMentorsRoute,
  AboutPressRoute: AboutPressRoute,
  AboutRewardsRoute: AboutRewardsRoute,
  AboutTeamRoute: AboutTeamRoute,
  AboutVisionRoadmapRoute: AboutVisionRoadmapRoute,
  AchieveImpactRoute: AchieveImpactRoute,
  AchieveReportsRoute: AchieveReportsRoute,
  AdminAssociatedWithRoute: AdminAssociatedWithRoute,
  AdminBoardRoute: AdminBoardRoute,
  AdminFindUsOnRoute: AdminFindUsOnRoute,
  AdminInfrastructureRoute: AdminInfrastructureRoute,
  AdminInternshipRegistrationRoute: AdminInternshipRegistrationRoute,
  AdminLatestEventsRoute: AdminLatestEventsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMentorsRoute: AdminMentorsRoute,
  AdminMeshNetworkRoute: AdminMeshNetworkRoute,
  AdminPartnersLogosRoute: AdminPartnersLogosRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminVisitorsRoute: AdminVisitorsRoute,
  ApproachOperationalModelRoute: ApproachOperationalModelRoute,
  EcosystemInfrastructureRoute: EcosystemInfrastructureRoute,
  EcosystemInvestorsRoute: EcosystemInvestorsRoute,
  EcosystemMentorsRoute: EcosystemMentorsRoute,
  EcosystemPartnersRoute: EcosystemPartnersRoute,
  EventsCalendarRoute: EventsCalendarRoute,
  EventsCaseStudiesRoute: EventsCaseStudiesRoute,
  EventsEventRegistrationRoute: EventsEventRegistrationRoute,
  EventsStartupsEventsRoute: EventsStartupsEventsRoute,
  ProgramsJoinUsRoute: ProgramsJoinUsRoute,
  ProgramsPitchToUsRoute: ProgramsPitchToUsRoute,
  StartupsBlogRoute: StartupsBlogRoute,
  StartupsStartupFundingRoute: StartupsStartupFundingRoute,
  StartupsStartupPortfolioRoute: StartupsStartupPortfolioRoute,
  StartupsStartupRegistrationRoute: StartupsStartupRegistrationRoute,
  StudentsDashboardRoute: StudentsDashboardRoute,
  StudentsInternshipRegistrationRoute: StudentsInternshipRegistrationRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
